spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop_night 
    username: phoneshop_night 
    password: phoneshop123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

      
      
